Use 1 as the default number of commits (git last)
This patch sets the default number of commits to 1, in case
no number of commits is specified on the command line (note
that this requires the bash shell, as it uses bash-specific
shell parameter expansion syntax)... avoiding the following
error message:

~ $ git last
error: -n requires an argument
~ $ git-last
error: -n requires an argument
~ $ _